const properties = [
  {
    "location": "8558 Pecan St.",
    "city": "London",
    "id": "1",
    "propertyName": "RCE theaters - 907 S Beckford Dr, Henderson, NC 27536",
    "roomsAvailable": "3",
    "beds": "4",
    "bathTub": "1",
    "squareFeet": "732",
    "rentPermonthinDollars": "7255",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366835/pexels-mo-eid-18391614_f7zwhp.jpg"
  },
  {
    "location": "8558 Pecan St.",
    "city": "London",
    "propertyName": "RCE theaters - 907 S Beckford Dr, Henderson, NC 27536",
    "roomsAvailable": "3",
    "beds": "4",
    "bathTub": "1",
    "squareFeet": "732",
    "rentPermonthinDollars": "7255",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366835/pexels-%D0%B4%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9-%D1%82%D1%80%D0%B5%D0%BF%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9-18395200_xrwr3x.jpg"
  },
  {
    "location": "8558 Pecan St.",
    "city": "London",
    "propertyName": "RCE theaters - 907 S Beckford Dr, Henderson, NC 27536",
    "roomsAvailable": "3",
    "beds": "4",
    "bathTub": "1",
    "squareFeet": "732",
    "rentPermonthinDollars": "7255",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366835/pexels-leander-18373821_egqbls.jpg"
  },
  {
    "location": "123 Main St.",
    "city": "New York",
    "propertyName": "Luxury Apartment 1",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1200",
    "rentPermonthinDollars": "3500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366835/pexels-life-of-pix-8155_vqmleu.jpg"
  },
  {
    "location": "456 Elm St.",
    "city": "Mumbai",
    "propertyName": "Cozy Studio",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "400",
    "rentPermonthinDollars": "800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366833/pexels-johannes-plenio-2816284_xen5xw.jpg"
  },
  {
    "location": "789 Oak St.",
    "city": "Paris",
    "propertyName": "Charming Apartment",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "600",
    "rentPermonthinDollars": "2000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366833/pexels-kendall-hoopes-635041_bratsl.jpg"
  },
  {
    "location": "101 Pine St.",
    "city": "London",
    "propertyName": "Spacious Townhouse in Central London",
    "roomsAvailable": "5",
    "beds": "4",
    "bathTub": "3",
    "squareFeet": "2000",
    "rentPermonthinDollars": "5500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366833/pexels-francesco-ungaro-449023_ytywnr.jpg"
  },
  {
    "location": "22 Maple St.",
    "city": "New York",
    "propertyName": "Downtown Loft",
    "roomsAvailable": "2",
    "beds": "2",
    "bathTub": "1",
    "squareFeet": "1000",
    "rentPermonthinDollars": "3000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366834/pexels-nancy-bourque-1209978_n0py0x.jpg"
  },
  {
    "location": "555 Oak St.",
    "city": "Mumbai",
    "propertyName": "Penthouse with a View",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1500",
    "rentPermonthinDollars": "4500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366832/pexels-dipinder-rainu-12460246_vdx8xl.jpg"
  },
  {
    "location": "777 Elm St.",
    "city": "Paris",
    "propertyName": "Historic Parisian Townhouse",
    "roomsAvailable": "6",
    "beds": "5",
    "bathTub": "3",
    "squareFeet": "2500",
    "rentPermonthinDollars": "6000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366832/pexels-chris-duan-12610188_i1jz3x.jpg"
  },
  {
    "location": "444 Birch St.",
    "city": "London",
    "propertyName": "Modern City Center Apartment",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1100",
    "rentPermonthinDollars": "4000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366832/pexels-ricky-esquivel-1604141_whvrkz.jpg"
  },
  {
    "location": "333 Cedar St.",
    "city": "New York",
    "propertyName": "Chic Studio in SoHo",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "500",
    "rentPermonthinDollars": "2200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366832/pexels-emmanuel-codden-18387485_zqouaf.jpg"
  },
  {
    "location": "999 Walnut St.",
    "city": "Mumbai",
    "propertyName": "Luxurious Beachfront Villa",
    "roomsAvailable": "7",
    "beds": "6",
    "bathTub": "4",
    "squareFeet": "3500",
    "rentPermonthinDollars": "8000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366831/pexels-rauf-allahverdiyev-2805285_uhxbja.jpg"
  },
  {
    "location": "777 Oak St.",
    "city": "Paris",
    "propertyName": "Elegant Haussmannian Apartment",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1400",
    "rentPermonthinDollars": "5000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366831/pexels-chait-goli-1796727_vph6ma.jpg"
  },
  {
    "location": "555 Pine St.",
    "city": "London",
    "propertyName": "Cozy Garden Cottage",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "800",
    "rentPermonthinDollars": "2800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417430_h8eeuz.jpg"
  },
  {
    "location": "888 Cedar St.",
    "city": "New York",
    "propertyName": "Sunny Loft with Skyline Views",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "750",
    "rentPermonthinDollars": "2800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/b_ute2dl.jpg"
  },
  {
    "location": "123 Elm St.",
    "city": "Mumbai",
    "propertyName": "Seaside Retreat",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1200",
    "rentPermonthinDollars": "4500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "456 Pine St.",
    "city": "Paris",
    "propertyName": "Art Deco Parisian Flat",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "1",
    "squareFeet": "900",
    "rentPermonthinDollars": "3500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366829/b2_ejcd4o.jpg"
  },
  {
    "location": "789 Oak St.",
    "city": "London",
    "propertyName": "Riverside Townhouse",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1100",
    "rentPermonthinDollars": "4200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366829/b3_wfafdp.jpg"
  },
  {
    "location": "101 Maple St.",
    "city": "New York",
    "propertyName": "Central Park View Apartment",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1300",
    "rentPermonthinDollars": "3900",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "222 Elm St.",
    "city": "Mumbai",
    "propertyName": "City Center Condo",
    "roomsAvailable": "2",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1000",
    "rentPermonthinDollars": "3000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "333 Oak St.",
    "city": "Paris",
    "propertyName": "Parisian Loft with Eiffel View",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "800",
    "rentPermonthinDollars": "2800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "444 Pine St.",
    "city": "London",
    "propertyName": "Chic Apartment in Covent Garden",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "700",
    "rentPermonthinDollars": "2600",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "555 Birch St.",
    "city": "New York",
    "propertyName": "Luxury Penthouse 2",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "3",
    "squareFeet": "1800",
    "rentPermonthinDollars": "4800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "666 Oak St.",
    "city": "Mumbai",
    "propertyName": "Modern City View Apartment",
    "roomsAvailable": "2",
    "beds": "2",
    "bathTub": "1",
    "squareFeet": "900",
    "rentPermonthinDollars": "2500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "777 Elm St.",
    "city": "Paris",
    "propertyName": "Eiffel Tower View Apartment",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "1",
    "squareFeet": "1000",
    "rentPermonthinDollars": "3200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "888 Pine St.",
    "city": "London",
    "propertyName": "Central London Studio",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "450",
    "rentPermonthinDollars": "1800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "999 Cedar St.",
    "city": "New York",
    "propertyName": "Loft in Historic Building",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "600",
    "rentPermonthinDollars": "2000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "123 Oak St.",
    "city": "Mumbai",
    "propertyName": "Sea View Retreat",
    "roomsAvailable": "5",
    "beds": "4",
    "bathTub": "2",
    "squareFeet": "1600",
    "rentPermonthinDollars": "4800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "456 Elm St.",
    "city": "Paris",
    "propertyName": "Chic Montmartre Apartment",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "650",
    "rentPermonthinDollars": "2200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "789 Pine St.",
    "city": "London",
    "propertyName": "Covent Garden Loft",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1000",
    "rentPermonthinDollars": "3800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "101 Oak St.",
    "city": "New York",
    "propertyName": "Luxury Condo with View",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1400",
    "rentPermonthinDollars": "4500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "222 Pine St.",
    "city": "Mumbai",
    "propertyName": "Downtown City View Studio",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "500",
    "rentPermonthinDollars": "1800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "333 Oak St.",
    "city": "Paris",
    "propertyName": "Charming Montparnasse Apartment",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "600",
    "rentPermonthinDollars": "2200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "444 Elm St.",
    "city": "London",
    "propertyName": "Stylish Camden Townhouse",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1200",
    "rentPermonthinDollars": "4000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "555 Pine St.",
    "city": "New York",
    "propertyName": "Downtown Luxury Loft",
    "roomsAvailable": "2",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1000",
    "rentPermonthinDollars": "3500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "666 Elm St.",
    "city": "Mumbai",
    "propertyName": "City Center Oasis",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "800",
    "rentPermonthinDollars": "2800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "777 Oak St.",
    "city": "Paris",
    "propertyName": "Romantic Seine View Studio",
    "roomsAvailable": "1",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "450",
    "rentPermonthinDollars": "1800",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "888 Pine St.",
    "city": "London",
    "propertyName": "Cozy Notting Hill Cottage",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "700",
    "rentPermonthinDollars": "2200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "999 Cedar St.",
    "city": "New York",
    "propertyName": "Soho Art Loft",
    "roomsAvailable": "3",
    "beds": "2",
    "bathTub": "2",
    "squareFeet": "1100",
    "rentPermonthinDollars": "3500",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "123 Elm St.",
    "city": "Mumbai",
    "propertyName": "Seaview Penthouse",
    "roomsAvailable": "4",
    "beds": "3",
    "bathTub": "2",
    "squareFeet": "1400",
    "rentPermonthinDollars": "4200",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "456 Pine St.",
    "city": "Paris",
    "propertyName": "Montmartre View Apartment",
    "roomsAvailable": "2",
    "beds": "1",
    "bathTub": "1",
    "squareFeet": "600",
    "rentPermonthinDollars": "2400",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  },
  {
    "location": "789 Oak St.",
    "city": "London",
    "propertyName": "Riverside Mansion",
    "roomsAvailable": "6",
    "beds": "4",
    "bathTub": "3",
    "squareFeet": "2500",
    "rentPermonthinDollars": "6000",
    "imageURL": "https://res.cloudinary.com/deumuo4ko/image/upload/v1696366830/pexels-pixabay-417344_bxufcn.jpg"
  }
];

export default properties;
